language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - git
    - g++
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
    - python-pip
    - wget
    - cmake
install:
  - export NUMBER_OF_PROCESSORS=8
  - install/modules.sh
  - export MODULESHOME=$HOME/packages/modules
  - export MODULEPATH=$HOME/modules
  - install/dcm2niix.sh
  - install/netrc.sh
  - cat $HOME/.netrc
  - install/mrtrix.sh
  - pip install .
  - mkdir -p $HOME/data
  - mkdir ./test/data
  - ln -s $HOME/xnat-cache ./test/data/cache
  - pip install nose
  - pip install codecov
script:
  nosetests test/unittests --with-coverage --cover-package=arcana
cache:
  directories:
    - $HOME/packages
    - $HOME/modules
    - $HOME/downloads
    - $HOME/xnat-cache
after_success:
  codecov
