language: python
sudo: required
services:
  - docker
matrix:
  include:
    - python: 2.7
env:
  global:
    - ARCANA_TEST_XNAT='https//xnat-dev.erc.monash.edu.au'
addons:
  apt:
    update: true
    packages:
    - git
    - g++
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
    - python-pip
    - wget
    - cmake
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m`  > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - export NUMBER_OF_PROCESSORS=8
  - ci/xnat.sh
  - ci/modules.sh
  - export MODULESHOME=$HOME/packages/modules
  - export MODULEPATH=$HOME/modules
  - ci/dcm2niix.sh
  - ci/netrc.sh
  - ci/mrtrix.sh
  - pip install .
  - mkdir -p $HOME/data
  - ln -s $HOME/xnat-cache ./test/data/cache
  - pip install nose
  - pip install codecov
  - python ci/wait_for_xnat.py
script:
  nosetests test/unittests --with-coverage --cover-package=arcana
cache:
  directories:
    - $HOME/packages
    - $HOME/modules
    - $HOME/downloads
    - $HOME/xnat-cache
after_success:
  codecov
