language: python
sudo: required
services:
  - docker
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
env:
  global:
    - ARCANA_TEST_XNAT='https://localhost'
    - DOCKER_COMPOSE_VERSION=1.21.2
addons:
  apt:
    packages:
    - git
    - g++
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
    - python-pip
    - wget
    - cmake
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`  > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - export NUMBER_OF_PROCESSORS=8
  - install/xnat.sh
  - install/modules.sh
  - export MODULESHOME=$HOME/packages/modules
  - export MODULEPATH=$HOME/modules
  - install/dcm2niix.sh
  - install/netrc.sh
  - install/mrtrix.sh
  - pip install .
  - mkdir -p $HOME/data
  - ln -s $HOME/xnat-cache ./test/data/cache
  - pip install nose
  - pip install codecov
script:
  nosetests test/unittests --with-coverage --cover-package=arcana
cache:
  directories:
    - $HOME/packages
    - $HOME/modules
    - $HOME/downloads
    - $HOME/xnat-cache
after_success:
  codecov
