language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - git
    - g++
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
    - python-pip
    - wget
    - cmake
install:
  - install/modules.sh
  - export MODULESHOME=$HOME/packages/modules
  - export MODULEPATH=$HOME/modules
  - install/dcm2niix.sh
  - install/netrc.sh
  - export NUMBER_OF_PROCESSORS=4
  - install/mrtrix.sh
  - pip install .
  - pip install nose
  - pip install codecov
  - export NUMBER_OF_PROCESSORS=1
script:
  nosetests test/unittests --with-coverage --cover-package=nianalysis
cache:
  directories:
    - $HOME/packages
    - $HOME/modules
    - $HOME/downloads
after_success:
  codecov
