language: python
sudo: required
services:
  - docker
matrix:
  include:
    - python: 2.7
      env: ARCANA_TEST_DATA=$HOME/data/py27
    - python: 3.5
      env: ARCANA_TEST_DATA=$HOME/data/py34
    - python: 3.6
      env: ARCANA_TEST_DATA=$HOME/data/py36
env:
  global:
    - XNAT_VER=1.7.4
    - ARCANA_TEST_XNAT=http://localhost
    - XNAT_DIR=$HOME/xnat
    - DOCKER_VER=1.21.2
    - MODULESHOME=$HOME/packages/modules
    - MODULEPATH=$HOME/modules
    - NUMBER_OF_PROCESSORS=8
addons:
  apt:
    update: true
    packages:
    - git
    - g++
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
    - python-pip
    - wget
    - cmake
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/$DOCKER_VER/docker-compose-`uname -s`-`uname -m`  > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install: 
  - ci/xnat.sh
  - pushd $XNAT_DIR; docker-compose up -d; popd
  - ci/modules.sh
  - ci/netrc.sh
  - pip install .
  - mkdir -p $HOME/data
  - pip install nose
  - pip install codecov
  - sed -i 's/^            _save_resultfile(result, outdir, self.name)/            print(result)\n            _save_resultfile(result, outdir, self.name)/g' /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py
  - python ci/wait_for_xnat.py
script:
  nosetests test/unittests --with-coverage --cover-package=arcana
after_script:
  - pushd $XNAT_DIR; docker-compose down; popd
cache:
  directories:
    - $HOME/packages
    - $HOME/modules
    - $HOME/downloads
after_success:
  codecov
